language: swift
osx_image: xcode9
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage update
script:
  - set -o pipefail && xcodebuild -project SomaFM.xcodeproj -scheme SomaFM CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
